//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for arduinoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="arduinoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mainShiftRegister" type="{}mainShiftRegisterType"/&gt;
 *         &lt;element name="panels" type="{}panelsType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "arduinoType", propOrder = {
    "mainShiftRegister",
    "panels"
})
public class ArduinoType {

    @XmlElement(required = true)
    protected MainShiftRegisterType mainShiftRegister;
    @XmlElement(required = true)
    protected PanelsType panels;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the mainShiftRegister property.
     * 
     * @return
     *     possible object is
     *     {@link MainShiftRegisterType }
     *     
     */
    public MainShiftRegisterType getMainShiftRegister() {
        return mainShiftRegister;
    }

    /**
     * Sets the value of the mainShiftRegister property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainShiftRegisterType }
     *     
     */
    public void setMainShiftRegister(MainShiftRegisterType value) {
        this.mainShiftRegister = value;
    }

    /**
     * Gets the value of the panels property.
     * 
     * @return
     *     possible object is
     *     {@link PanelsType }
     *     
     */
    public PanelsType getPanels() {
        return panels;
    }

    /**
     * Sets the value of the panels property.
     * 
     * @param value
     *     allowed object is
     *     {@link PanelsType }
     *     
     */
    public void setPanels(PanelsType value) {
        this.panels = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
