//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for configurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configurationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="arduinos" type="{}arduinosType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configurationType", propOrder = {
    "arduinos"
})
@XmlRootElement
public class ConfigurationType {

    @XmlElement(required = true)
    protected ArduinosType arduinos;

    /**
     * Gets the value of the arduinos property.
     * 
     * @return
     *     possible object is
     *     {@link ArduinosType }
     *     
     */
    public ArduinosType getArduinos() {
        return arduinos;
    }

    /**
     * Sets the value of the arduinos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArduinosType }
     *     
     */
    public void setArduinos(ArduinosType value) {
        this.arduinos = value;
    }

}
