//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for indicatorStateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="indicatorStateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="arduinoMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="proSimMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "indicatorStateType", propOrder = {
    "arduinoMessage",
    "proSimMessage"
})
public class IndicatorStateType {

    @XmlElement(required = true)
    protected String arduinoMessage;
    @XmlElement(required = true)
    protected String proSimMessage;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the arduinoMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArduinoMessage() {
        return arduinoMessage;
    }

    /**
     * Sets the value of the arduinoMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArduinoMessage(String value) {
        this.arduinoMessage = value;
    }

    /**
     * Gets the value of the proSimMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProSimMessage() {
        return proSimMessage;
    }

    /**
     * Sets the value of the proSimMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProSimMessage(String value) {
        this.proSimMessage = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
