//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for indicatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="indicatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mainShiftRegisterName"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="SR1"/&gt;
 *               &lt;enumeration value="SR2"/&gt;
 *               &lt;enumeration value="SR3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="auxShiftRegisterName"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="ASR1"/&gt;
 *               &lt;enumeration value="ASR2"/&gt;
 *               &lt;enumeration value="ASR3"/&gt;
 *               &lt;enumeration value="ASR4"/&gt;
 *               &lt;enumeration value="ASR5"/&gt;
 *               &lt;enumeration value="ASR6"/&gt;
 *               &lt;enumeration value="ASR7"/&gt;
 *               &lt;enumeration value="ASR8"/&gt;
 *               &lt;enumeration value="ASR9"/&gt;
 *               &lt;enumeration value="ASR10"/&gt;
 *               &lt;enumeration value="ASR11"/&gt;
 *               &lt;enumeration value="ASR12"/&gt;
 *               &lt;enumeration value="ASR13"/&gt;
 *               &lt;enumeration value="ASR14"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="auxShiftRegisterPin"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="0"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *               &lt;enumeration value="6"/&gt;
 *               &lt;enumeration value="7"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="shiftRegisterValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="transistorNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="indicatorStates" type="{}indicatorStatesType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "indicatorType", propOrder = {
    "mainShiftRegisterName",
    "auxShiftRegisterName",
    "auxShiftRegisterPin",
    "shiftRegisterValue",
    "transistorNumber",
    "indicatorStates"
})
public class IndicatorType {

    @XmlElement(required = true)
    protected String mainShiftRegisterName;
    @XmlElement(required = true)
    protected String auxShiftRegisterName;
    @XmlElement(required = true)
    protected String auxShiftRegisterPin;
    @XmlElement(required = true)
    protected String shiftRegisterValue;
    @XmlElement(required = true)
    protected String transistorNumber;
    @XmlElement(required = true)
    protected IndicatorStatesType indicatorStates;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the mainShiftRegisterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainShiftRegisterName() {
        return mainShiftRegisterName;
    }

    /**
     * Sets the value of the mainShiftRegisterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainShiftRegisterName(String value) {
        this.mainShiftRegisterName = value;
    }

    /**
     * Gets the value of the auxShiftRegisterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxShiftRegisterName() {
        return auxShiftRegisterName;
    }

    /**
     * Sets the value of the auxShiftRegisterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxShiftRegisterName(String value) {
        this.auxShiftRegisterName = value;
    }

    /**
     * Gets the value of the auxShiftRegisterPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxShiftRegisterPin() {
        return auxShiftRegisterPin;
    }

    /**
     * Sets the value of the auxShiftRegisterPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxShiftRegisterPin(String value) {
        this.auxShiftRegisterPin = value;
    }

    /**
     * Gets the value of the shiftRegisterValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShiftRegisterValue() {
        return shiftRegisterValue;
    }

    /**
     * Sets the value of the shiftRegisterValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShiftRegisterValue(String value) {
        this.shiftRegisterValue = value;
    }

    /**
     * Gets the value of the transistorNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransistorNumber() {
        return transistorNumber;
    }

    /**
     * Sets the value of the transistorNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransistorNumber(String value) {
        this.transistorNumber = value;
    }

    /**
     * Gets the value of the indicatorStates property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorStatesType }
     *     
     */
    public IndicatorStatesType getIndicatorStates() {
        return indicatorStates;
    }

    /**
     * Sets the value of the indicatorStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorStatesType }
     *     
     */
    public void setIndicatorStates(IndicatorStatesType value) {
        this.indicatorStates = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
