//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for mainShiftRegisterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mainShiftRegisterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serPin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="clkPin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="srclkPin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="auxShiftRegisters" type="{}auxShiftRegistersType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mainShiftRegisterType", propOrder = {
    "serPin",
    "clkPin",
    "srclkPin",
    "auxShiftRegisters"
})
public class MainShiftRegisterType {

    @XmlElement(required = true)
    protected String serPin;
    @XmlElement(required = true)
    protected String clkPin;
    @XmlElement(required = true)
    protected String srclkPin;
    @XmlElement(required = true)
    protected AuxShiftRegistersType auxShiftRegisters;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the serPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerPin() {
        return serPin;
    }

    /**
     * Sets the value of the serPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerPin(String value) {
        this.serPin = value;
    }

    /**
     * Gets the value of the clkPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClkPin() {
        return clkPin;
    }

    /**
     * Sets the value of the clkPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClkPin(String value) {
        this.clkPin = value;
    }

    /**
     * Gets the value of the srclkPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrclkPin() {
        return srclkPin;
    }

    /**
     * Sets the value of the srclkPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrclkPin(String value) {
        this.srclkPin = value;
    }

    /**
     * Gets the value of the auxShiftRegisters property.
     * 
     * @return
     *     possible object is
     *     {@link AuxShiftRegistersType }
     *     
     */
    public AuxShiftRegistersType getAuxShiftRegisters() {
        return auxShiftRegisters;
    }

    /**
     * Sets the value of the auxShiftRegisters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuxShiftRegistersType }
     *     
     */
    public void setAuxShiftRegisters(AuxShiftRegistersType value) {
        this.auxShiftRegisters = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
