//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for panelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="panelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="indicators" type="{}indicatorsType" minOccurs="0"/&gt;
 *         &lt;element name="switches" type="{}switchesType" minOccurs="0"/&gt;
 *         &lt;element name="rotaryEncoders" type="{}rotaryEncodersType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "panelType", propOrder = {
    "indicators",
    "switches",
    "rotaryEncoders"
})
public class PanelType {

    protected IndicatorsType indicators;
    protected SwitchesType switches;
    protected RotaryEncodersType rotaryEncoders;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the indicators property.
     * 
     * @return
     *     possible object is
     *     {@link IndicatorsType }
     *     
     */
    public IndicatorsType getIndicators() {
        return indicators;
    }

    /**
     * Sets the value of the indicators property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicatorsType }
     *     
     */
    public void setIndicators(IndicatorsType value) {
        this.indicators = value;
    }

    /**
     * Gets the value of the switches property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchesType }
     *     
     */
    public SwitchesType getSwitches() {
        return switches;
    }

    /**
     * Sets the value of the switches property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchesType }
     *     
     */
    public void setSwitches(SwitchesType value) {
        this.switches = value;
    }

    /**
     * Gets the value of the rotaryEncoders property.
     * 
     * @return
     *     possible object is
     *     {@link RotaryEncodersType }
     *     
     */
    public RotaryEncodersType getRotaryEncoders() {
        return rotaryEncoders;
    }

    /**
     * Sets the value of the rotaryEncoders property.
     * 
     * @param value
     *     allowed object is
     *     {@link RotaryEncodersType }
     *     
     */
    public void setRotaryEncoders(RotaryEncodersType value) {
        this.rotaryEncoders = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
