//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for rotaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rotaryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="inputPin"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="A0"/&gt;
 *               &lt;enumeration value="A1"/&gt;
 *               &lt;enumeration value="A2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="rotaryStates" type="{}rotaryStatesType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rotaryType", propOrder = {
    "inputPin",
    "rotaryStates"
})
public class RotaryType {

    @XmlElement(required = true)
    protected String inputPin;
    @XmlElement(required = true)
    protected RotaryStatesType rotaryStates;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the inputPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputPin() {
        return inputPin;
    }

    /**
     * Sets the value of the inputPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputPin(String value) {
        this.inputPin = value;
    }

    /**
     * Gets the value of the rotaryStates property.
     * 
     * @return
     *     possible object is
     *     {@link RotaryStatesType }
     *     
     */
    public RotaryStatesType getRotaryStates() {
        return rotaryStates;
    }

    /**
     * Sets the value of the rotaryStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link RotaryStatesType }
     *     
     */
    public void setRotaryStates(RotaryStatesType value) {
        this.rotaryStates = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
