//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 11:29:50 PM CEST 
//


package types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for switchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="switchType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="switchStates" type="{}switchStatesType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "switchType", propOrder = {
    "switchStates"
})
public class SwitchType {

    @XmlElement(required = true)
    protected SwitchStatesType switchStates;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the switchStates property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchStatesType }
     *     
     */
    public SwitchStatesType getSwitchStates() {
        return switchStates;
    }

    /**
     * Sets the value of the switchStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchStatesType }
     *     
     */
    public void setSwitchStates(SwitchStatesType value) {
        this.switchStates = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
